AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: "Name of an existing key pair to enable ssh access"
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: "Must be the name of an existing key pair"
Resources:
  PentestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: true
      EnableDnsSupport: true
  PublicSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref PentestVPC
      GroupDescription: 'Public Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 10.0.0.64/26
  PrivateSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref PentestVPC
      GroupDescription: 'Private Security Group'
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PentestVPC
      CidrBlock: 10.0.0.0/26
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PentestVPC
      CidrBlock: 10.0.0.64/26
  NetworkACL:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref PentestVPC
  PublicRT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref PentestVPC
  PrivateRT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref PentestVPC
  PentestIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
  VPCGWAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref PentestIGW
      VpcId: !Ref PentestVPC
  IPAddress:
    Type: AWS::EC2::EIP
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref IPAddress
      InstanceId: !Ref Kali
  Kali:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-04c879e4c1bc41d98
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: PublicSG
      SubnetId:
        Ref: PublicSubnet
  Ubuntu:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-07a3bd4944eb120a0
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: PrivateSG
      SubnetId:
        Ref: PrivateSubnet
